version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/data"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/frodskaparrit"
    schedule:
      interval: "daily"
